defmodule PairingsEngineWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :pairings_engine

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  # `secure: true` marks the session cookie https-only. It's set in prod (see
  # config/prod.exs) and left off in dev/test, which run over plain http —
  # a `secure` cookie would never be sent there, breaking login locally.
  # Defence in depth on top of the `force_ssl`/HSTS already configured in
  # config/prod.exs.
  # `max_age` makes the cookie persistent (survives the browser process
  # dying), not just session-scoped — without it, mobile browsers that kill
  # the tab in the background drop the cookie and boot the arbiter/helper
  # back to a login or enrollment-code screen mid-tournament. 30 days comfortably
  # outlives any single event; re-authenticating (login, or a fresh enrollment
  # code) still works at any time regardless.
  @session_options [
    store: :cookie,
    key: "_pairings_engine_key",
    signing_salt: "Uti9o2Qk",
    same_site: "Lax",
    max_age: 60 * 60 * 24 * 30,
    secure: Application.compile_env(:pairings_engine, :secure_cookies, false)
  ]

  # `:peer_data` and `:x_headers` are what let a LiveView work out who it is
  # talking to (`PairingsEngineWeb.ClientIp`), which the log-in page needs to
  # rate-limit magic-link sends. Without them `get_connect_info/2` returns
  # nil and every visitor looks alike.
  @connect_info [:peer_data, :x_headers, session: @session_options]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: @connect_info],
    longpoll: [connect_info: @connect_info]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :pairings_engine,
    gzip: not code_reloading?,
    only: PairingsEngineWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :pairings_engine
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug PairingsEngineWeb.Router
end
