defmodule PairingsEngineWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :pairings_engine

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  # `secure: true` marks the session cookie https-only. It's set in prod (see
  # config/prod.exs) and left off in dev/test, which run over plain http -
  # a `secure` cookie would never be sent there, breaking login locally.
  # Defence in depth on top of the `force_ssl`/HSTS already configured in
  # config/prod.exs.
  # `max_age` makes the cookie persistent (survives the browser process
  # dying), not just session-scoped - without it, mobile browsers that kill
  # the tab in the background drop the cookie and boot the arbiter/helper
  # back to a login or enrollment-code screen mid-tournament. 30 days comfortably
  # outlives any single event; re-authenticating (login, or a fresh enrollment
  # code) still works at any time regardless.
  @session_options [
    store: :cookie,
    key: "_pairings_engine_key",
    signing_salt: "Uti9o2Qk",
    same_site: "Lax",
    max_age: 60 * 60 * 24 * 30,
    secure: Application.compile_env(:pairings_engine, :secure_cookies, false)
  ]

  # `:peer_data` and `:x_headers` are what let a LiveView work out who it is
  # talking to (`PairingsEngineWeb.ClientIp`), which the log-in page needs to
  # rate-limit magic-link sends. Without them `get_connect_info/2` returns
  # nil and every visitor looks alike.
  @connect_info [:peer_data, :x_headers, session: @session_options]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: @connect_info],
    longpoll: [connect_info: @connect_info]

  # A second LiveView socket for the embeddable public pages, WITHOUT the
  # session in `connect_info`.
  #
  # The session cookie is `same_site: "Lax"` (above), which by design is not
  # sent on a cross-site request - and an <iframe> on someone else's domain
  # is exactly that. So on the embeddable pages (`/p/:slug/pairings` and
  # `/p/:slug/standings`, see PairingsEngineWeb.CSP) the "/live" socket
  # above connects with `session: nil`, LiveView cannot verify the session
  # token it was handed, rejects the connect, and the client retries
  # forever: a websocket that closes before it opens, the topbar flashing
  # on every attempt, and the page appearing to reload constantly.
  #
  # Relaxing the cookie to `same_site: "None"` would fix it and is the wrong
  # trade - that would send the session cookie to every third-party frame in
  # existence, weakening CSRF protection for the whole app (including every
  # authenticated page) to serve two read-only ones. Instead these pages get
  # a socket that never wanted the session in the first place.
  #
  # Safe because of what these pages are: no login and no per-user state -
  # `mount_current_scope` resolves to an anonymous scope whether or not a
  # session is present, so nothing is lost by not having one.
  #
  # `/p/:slug/register` joined them on 2026-08-22, and it DOES write, so the
  # old shorthand "no writes" no longer describes this list. What actually
  # matters is unchanged: the write takes no authority from the visitor's
  # session, because there is none to take. It is gated on
  # `registration_open` and rate-limited per IP, neither of which has
  # anything to do with which socket carried it. Any page that genuinely
  # DEPENDS on the session keeps using "/live"; `assets/js/app.js` picks
  # between them by path.
  socket "/embed/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, :x_headers]],
    longpoll: [connect_info: [:peer_data, :x_headers]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :pairings_engine,
    gzip: not code_reloading?,
    only: PairingsEngineWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :pairings_engine
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug PairingsEngineWeb.Router
end
