defmodule PairingsEngine.RoundRobin do
  @moduledoc """
  Round-robin (Berger table) pairing engine.

  `PairingsEngine.Pairing.pair_next_round/1` dispatches here for any
  tournament with `pairing_system: "round_robin"`.

  ## The schedule

  FIDE only publishes finished Berger tables (Handbook C.05 Annex 1, for
  2..16-ish players) rather than a formula, but they're generated by a
  well-defined "circle method" construction that this module reimplements
  and has been verified against the published tables for N=4 and N=6 (see
  `test/pairings_engine/round_robin_test.exs`):

    * Players are numbered 1..N by their frozen `pairing_number` (see
      "Freezing" below). If N is odd, a phantom player numbered N+1 is
      added to make the count even - FIDE's own rule ("where there is an
      odd number of players, the highest number counts as a bye").
    * `effective_n` = N (even) or N+1 (odd); `m = effective_n - 1` (always
      odd, since `effective_n` is always even) is both the number of
      rounds in one cycle and the modulus for the round-robin arithmetic.
    * Player `effective_n` (the highest number - real when N is even, the
      phantom when N is odd) is the *fixed* player: in round `r`
      (0-indexed), it plays whichever real player `f(r) = (r * inv2) rem m`
      is (where `inv2` is the modular inverse of 2 mod `m`, i.e.
      `(m + 1) / 2` since `m` is odd) - this is a bijection over `r`, so
      every player takes the fixed player's opponent slot exactly once per
      cycle. When the fixed player is the phantom, that real opponent gets
      the round's structural bye instead of a real pairing.
    * Every other player `i` (0-indexed label, real number `i + 1`) not
      equal to `f(r)` pairs with `j` such that `i + j ≡ r (mod m)` - the
      remaining `m - 1` labels split into `(m - 1) / 2` such pairs.
    * Colour: for the fixed pairing, the fixed player is White iff `r` is
      odd. For every other pair `(i, j)` with `i < j`, White is the
      lower-numbered player `i` iff `j - i` is odd, otherwise the
      higher-numbered player `j`. Both rules were reverse-engineered from
      the FIDE-published N=4 and N=6 tables and hold for every pair in
      both (all four possible `j - i` distances for N=6, both possible
      distances for N=4) - see `docs/pairing-systems.md`.

  All of this lives in `schedule/3`, which is a **pure** function of
  `(player_count, cycles, round_number)` - pairing round K always produces
  the same result, satisfying the correctness rule that a round-robin
  schedule must not depend on when it's computed.

  ## Freezing pairing numbers

  Exactly like the Swiss path (`PairingsEngine.Pairing`), pairing numbers
  are assigned once - highest rating first, name as the tie-break (FIDE
  C.04.2.B) - and then frozen forever. Unlike Swiss, round robin never
  assigns numbers to anyone after that first freeze: the schedule is fixed
  the moment round 1 is first paired, and it would be structurally
  impossible to slot a newcomer into an already-computed Berger table
  without changing everyone else's opponents. Players who join after the
  freeze are simply excluded from every round of the schedule (see
  `docs/pairing-systems.md`).

  The arbiter can set the numbers before round 1 instead - by hand or by a
  drawing of lots (`PairingsEngine.StartingNumbers`, C.05 6.2). Numbers
  found on the roster when round 1 is paired are used as they are; only
  the players still without one are numbered, after them.

  ## One table per category, and SWAR's table

  Pairing by category (`pair_by_category`), each category plays its own
  Berger table, numbered by pairing number within it
  (`schedule_groups/2`) - SWAR's round robin with separate categories.
  `schedule/3` is SWAR's own `GenerationBerger` (`PairingRobin.cpp`),
  colours included, and a SWAR import numbers players by SWAR's Rank, so a
  round robin continued from a `.swar` file plays the rounds SWAR would have
  (docs/pairing-systems.md).

  ## Byes

  Odd player counts always produce exactly one structural, zero-point bye
  per player per cycle (never zero, never two) - see `schedule/3`'s doc.
  It's recorded as a `"requested-zero"` row in the `byes` table (TRF code
  `Z`, 0 points via `PairingsEngine.Standings`/`PairingsEngine.Pairing`'s
  existing bye-type handling) with no corresponding `pairings` row - the
  same shape Swiss already uses for a round-specific requested absence.
  `"pairing-allocated"` (a full point) is deliberately not used: this bye
  isn't the pairing engine running out of opponents, it's a structural
  feature of an odd-sized round-robin, and giving it a free point would
  be unfair to the N-1 (or N, if N even) players who never get one.

  The one exception is a round robin imported from SWAR, which forces its
  free round to a full point (`SwarImport.scoring_attrs/1`): its free
  rounds stay bye boards worth `bye_value`, like the ones it was imported
  with (`swar_bye?/1`).
  """

  import Ecto.Query
  alias PairingsEngine.{Repo, Tournaments}
  # `Pairing` is already the schema in this module; the round-lifecycle
  # module borrows the same name, so it comes in as `Engine` - the alias
  # PairingsLive and the mobile screen already use for it.
  alias PairingsEngine.Pairing, as: Engine
  alias PairingsEngine.Tournaments.{Player, Round, Pairing, Tournament}

  @doc """
  Pairs the next round using a Berger round-robin schedule.

  Unlike Swiss, a round-robin round's pairings never depend on prior
  results (the whole schedule is fixed at freeze time - see moduledoc), so
  there's no need to gate pairing round N+1 on round N being fully scored
  the way the Swiss/JaVaFo path does - see `pair_all_rounds/1` below,
  which is exactly this fact turned into a feature (generate the whole
  event in one action, since there's nothing to wait on between rounds).

  `tournament.rounds_count` isn't a free choice the way it is for Swiss -
  a round-robin's real length is entirely determined by the frozen player
  count plus cycles/match-format, the moment freezing happens (see
  `ensure_frozen/1`). This corrects `rounds_count` to that real total on
  every call (a no-op once it already matches, which is every call after
  the first), so an arbiter who left the tournament-creation form's
  generic default in place doesn't end up with a round picker showing
  more rounds than a Berger table for their actual roster will ever have.
  """
  @spec pair_next_round(Tournament.t()) :: {:ok, Round.t()} | {:error, term()}
  def pair_next_round(%Tournament{} = tournament) do
    if Tournament.team_round_robin?(tournament) do
      PairingsEngine.TeamRoundRobin.pair_next_round(tournament)
    else
      pair_individual_next_round(tournament)
    end
  end

  defp pair_individual_next_round(tournament) do
    ensure_frozen(tournament)
    frozen = frozen_players(tournament.id)

    case ensure_correct_rounds_count(tournament, schedule_groups(tournament, frozen)) do
      {:error, reason} -> {:error, reason}
      tournament -> do_pair_next_round(tournament, frozen)
    end
  end

  defp do_pair_next_round(tournament, frozen) do
    paired = PairingsEngine.Pairing.paired_rounds_count(tournament.id)
    next_number = paired + 1

    cond do
      next_number > tournament.rounds_count ->
        {:error, {:all_rounds_paired, tournament.rounds_count}}

      length(frozen) < 2 ->
        {:error, "At least two active players are needed"}

      true ->
        do_pair(tournament, frozen, next_number)
    end
  end

  @doc """
  Pairs every remaining round of the Berger schedule in one call - the
  whole point of round-robin pairing never depending on prior results
  (see moduledoc and `pair_next_round/1`'s doc): there's no reason to make
  an arbiter click "pair" once per round when the entire schedule is
  already fully determined the moment player freezing happens.

  Returns `{:ok, last_round_number}` once the schedule is fully paired
  (idempotent - calling this again once everything is already paired
  returns the same `{:ok, last_round_number}`, not an error), or
  `{:error, reason}` from whichever round first failed to pair (nothing
  after that point gets attempted; every round up to it is still paired -
  each round's own insertion is already a self-contained transaction, see
  `create_round/4`).
  """
  @spec pair_all_rounds(Tournament.t()) :: {:ok, pos_integer()} | {:error, term()}
  # Gated here as well as in `Pairing.pair_next_round/1`, because this is a
  # second entry point: `PairingsEngineWeb.PairingsLive` calls it directly,
  # so a tournament frozen read-only would otherwise reach the schedule
  # writes below without passing the gate at all. Like its sibling there,
  # this used to pattern-match `archived_at` rather than asking
  # `Tournaments.ensure_writable/1`, and so did not know a handed-off
  # tournament from a live one.
  def pair_all_rounds(%Tournament{} = tournament) do
    case Tournaments.ensure_writable(tournament) do
      :ok ->
        # A team round robin runs the same Berger table over teams - see
        # `PairingsEngine.TeamRoundRobin`. Branched after the gate, so the
        # gate covers both.
        if Tournament.team_round_robin?(tournament),
          do: PairingsEngine.TeamRoundRobin.pair_all_rounds(tournament),
          else: do_pair_all_rounds(tournament)

      {:error, reason} ->
        {:error, Tournaments.refusal_message(reason, "pairing")}
    end
  end

  defp do_pair_all_rounds(%Tournament{} = tournament) do
    # Freeze, read the roster and correct `rounds_count` ONCE, then loop on
    # the corrected struct.
    #
    # This used to recurse into `pair_next_round/1` with the ORIGINAL
    # tournament every time. `ensure_correct_rounds_count/2` returns a
    # corrected struct, but that correction was local to each call and never
    # reached the caller, so every round re-detected the same mismatch and
    # wrote it again - and `update_tournament/2` fires
    # `broadcast_tournament_change(:settings)` plus
    # `broadcast_user_tournaments/1` on every write. A 14-player double round
    # robin issued 26 redundant writes and 52 redundant broadcasts inside one
    # click of a shipped button, along with a `Repo.exists?` and a roster read
    # per round. Nothing broke; the loop terminated on `paired_rounds_count`
    # either way. It was all work thrown away.
    #
    # Holding the struct constant across the loop is safe because nothing in
    # the loop changes what it carries: the frozen set cannot change (that is
    # what frozen means), and `do_pair/3` reads `rr_match_format`/`rr_cycles`
    # and writes rounds, never the tournament.
    ensure_frozen(tournament)
    frozen = frozen_players(tournament.id)

    case ensure_correct_rounds_count(tournament, schedule_groups(tournament, frozen)) do
      {:error, reason} -> {:error, reason}
      corrected -> pair_remaining(corrected, frozen)
    end
  end

  defp pair_remaining(tournament, frozen) do
    case tournament |> do_pair_next_round(frozen) |> after_step() do
      :continue -> pair_remaining(tournament, frozen)
      :schedule_complete -> {:ok, Engine.paired_rounds_count(tournament.id)}
      {:error, _reason} = error -> error
    end
  end

  @doc false
  # What one round's result means for the loop in `pair_all_rounds/1`.
  #
  # Matched on the TAG. This used to be `{:error, "All " <> _}`, which read
  # "the schedule is finished" off the first four bytes of an English
  # sentence - so any refusal that happened to start with "All" ("All
  # players are withdrawn", say) would have been reported to the arbiter as
  # a successfully paired schedule, and wrapping the sentence in gettext
  # would have turned the real finish into an error in every other language.
  #
  # Public only so a test can hand it a reason no producer emits today.
  def after_step({:ok, _round}), do: :continue
  def after_step({:error, {:all_rounds_paired, _rounds}}), do: :schedule_complete
  def after_step({:error, _reason} = error), do: error

  @doc """
  Computes the Berger schedule for `round_number` (1-indexed, spanning
  however many `cycles` the tournament plays - see `tournaments.rr_cycles`)
  over `player_count` schedulable (frozen) players numbered 1..player_count.

  Pure: touches no database, depends only on these three integers. Returns
  `{:ok, matches}` where each entry is `{:pairing, white_number,
  black_number}` (both 1-indexed pairing numbers) or `{:bye, player_number}`
  (the odd-N structural bye), or `{:error, {:all_rounds_paired, total}}` once
  every round of the schedule has already been returned - the same reason,
  with the same meaning, that `PairingsEngine.Pairing.pair_next_round/1`
  gives for a finished tournament of any system.

  Option `:reverse_last_two?` - FIDE C.05 Annex 1's recommendation for a
  double round robin ("it is recommended to reverse the order of the last
  two rounds of the first cycle"), `tournaments.rr_reverse_last_two`: rounds
  `m - 1` and `m` of the first cycle (`m` the cycle's length) are played in
  each other's place, so a player who would otherwise have the same colour
  in the first cycle's last round and the second cycle's first two does
  not. The second cycle is the table's own order, colours reversed - TRF26's
  FIDE_DOUBLEROUNDROBIN, and `Ainalrami.Berger.round/4`'s construction.
  Ignored for a single cycle and for a cycle shorter than two rounds;
  without it the schedule is exactly what it always was.
  """
  @spec schedule(pos_integer(), pos_integer(), pos_integer(), keyword()) ::
          {:ok, [{:pairing, pos_integer(), pos_integer()} | {:bye, pos_integer()}]}
          | {:error, {:all_rounds_paired, pos_integer()}}
  def schedule(player_count, cycles, round_number, opts \\ [])

  def schedule(player_count, cycles, round_number, opts) when player_count >= 2 do
    effective_n = if rem(player_count, 2) == 0, do: player_count, else: player_count + 1
    dummy_number = if rem(player_count, 2) == 1, do: effective_n, else: nil
    cycle_length = effective_n - 1
    total_rounds = cycle_length * cycles

    if round_number > total_rounds do
      {:error, {:all_rounds_paired, total_rounds}}
    else
      cycle_index = div(round_number - 1, cycle_length)
      r = Integer.mod(round_number - 1, cycle_length)
      reverse_colours? = rem(cycle_index, 2) == 1

      r =
        if Keyword.get(opts, :reverse_last_two?, false) and cycles >= 2 and cycle_index == 0 and
             cycle_length >= 2,
           do: swap_last_two(r, cycle_length),
           else: r

      {:ok, round_matches(effective_n, dummy_number, r, reverse_colours?)}
    end
  end

  defp swap_last_two(r, cycle_length) when r == cycle_length - 1, do: cycle_length - 2
  defp swap_last_two(r, cycle_length) when r == cycle_length - 2, do: cycle_length - 1
  defp swap_last_two(r, _cycle_length), do: r

  @doc """
  The size of the Berger table a round robin under way runs over: its
  numbered teams for a team round robin, else the largest of its frozen
  players' groups (`schedule_groups/2`). 0 before anything is frozen.
  """
  def frozen_schedule_size(%Tournament{} = tournament) do
    if Tournament.team_round_robin?(tournament) do
      # A plugin's table (`PairingsEngine.Plugins.team_schedule/1`) can be
      # larger than the field, its empty numbers byes: its size is the
      # schedule's.
      case PairingsEngine.Plugins.team_schedule(tournament) do
        %{size: size} when is_integer(size) ->
          max(size, length(PairingsEngine.TeamRounds.numbered_teams(tournament.id)))

        _ ->
          length(PairingsEngine.TeamRounds.numbered_teams(tournament.id))
      end
    else
      tournament
      |> schedule_groups(frozen_players(tournament.id))
      |> Enum.map(&length/1)
      |> Enum.max(fn -> 0 end)
    end
  end

  @doc """
  The rounds a round robin of `size` needs with these settings - one cycle,
  two, or match format (`match_total_rounds/1`). `settings` is anything
  with `rr_cycles` and `rr_match_format`.
  """
  def rounds_needed(size, %{rr_match_format: true}), do: match_total_rounds(size)
  def rounds_needed(size, %{rr_cycles: cycles}), do: total_rounds(size, cycles || 1)

  @doc "Total number of rounds the full schedule needs for `player_count` players over `cycles` cycles."
  def total_rounds(player_count, cycles) do
    effective_n = if rem(player_count, 2) == 0, do: player_count, else: player_count + 1
    (effective_n - 1) * cycles
  end

  @doc """
  "Match format" schedule: like `schedule/3` but every single-cycle pairing
  is played twice, back-to-back, colours reversed, instead of once -
  `tournaments.rr_match_format`, a different shape from `rr_cycles == 2`
  (see the moduledoc and the field's own doc comment on
  `PairingsEngine.Tournaments.Tournament`).

  `physical_round` is the round number as actually paired/displayed (1, 2,
  3, 4, ... - nothing here renumbers rounds). Physical rounds `2k-1` and
  `2k` are match `k`'s two legs: `match_number = div(physical_round + 1, 2)`
  maps both `2k-1` and `2k` to `k`, and `schedule(player_count, 1, k)` gives
  that match's pairing exactly once (a single-cycle Berger table, since a
  "match" here is one cycle's worth of pairing repeated, not two cycles).
  The odd physical round is leg 1, played exactly as the single-cycle
  schedule says; the even physical round is leg 2, the same pairing with
  colours swapped (`mirror_leg/1`).

  A structural bye (odd player count) mirrors unchanged rather than
  swapping anything - the player sitting out match `k` sits out both of its
  legs identically, so leg 2's bye row is the same player, same
  `"requested-zero"` type, just recorded against the next round number by
  the caller (`do_pair/2` inserts one row per physical round, same as
  `schedule/3`).
  """
  @spec match_schedule(pos_integer(), pos_integer()) ::
          {:ok, [{:pairing, pos_integer(), pos_integer()} | {:bye, pos_integer()}]}
          | {:error, {:all_rounds_paired, pos_integer()}}
  def match_schedule(player_count, physical_round) when physical_round >= 1 do
    match_number = div(physical_round + 1, 2)

    case schedule(player_count, 1, match_number) do
      {:ok, matches} ->
        leg2? = rem(physical_round, 2) == 0
        {:ok, if(leg2?, do: Enum.map(matches, &mirror_leg/1), else: matches)}

      # `schedule/3` counted matches; the tournament plays two rounds each.
      {:error, {:all_rounds_paired, matches}} ->
        {:error, {:all_rounds_paired, matches * 2}}
    end
  end

  defp mirror_leg({:pairing, w, b}), do: {:pairing, b, w}
  defp mirror_leg({:bye, _} = bye), do: bye

  @doc """
  Total number of physical rounds the match-format schedule needs for
  `player_count` players - exactly double `total_rounds(player_count, 1)`,
  since every single-cycle pairing becomes two physical rounds (its two
  legs). Match format is always a single Berger cycle underneath (see
  `match_schedule/2`), so unlike `total_rounds/2` there's no `cycles`
  parameter here.
  """
  @spec match_total_rounds(pos_integer()) :: pos_integer()
  def match_total_rounds(player_count) do
    total_rounds(player_count, 1) * 2
  end

  ## ---------- pure schedule construction ----------

  # See the moduledoc for the derivation of both the pairing and the
  # colour rule. `effective_n` is always even; `dummy_number` is
  # `effective_n` itself when the real player count was odd, else `nil`.
  defp round_matches(effective_n, dummy_number, r, reverse_colours?) do
    m = effective_n - 1
    inv2 = div(m + 1, 2)
    f = Integer.mod(r * inv2, m)

    fixed = {effective_n, f + 1, rem(r, 2) == 1}

    other =
      0..(m - 1)
      |> Enum.reject(&(&1 == f))
      |> Enum.map(fn i -> {i, Integer.mod(r - i, m)} end)
      |> Enum.filter(fn {i, j} -> i < j end)
      |> Enum.map(fn {i, j} -> {i + 1, j + 1, rem(j - i, 2) == 1} end)

    [fixed | other]
    |> Enum.map(fn {a, b, a_white?} ->
      white_is_a? = a_white? != reverse_colours?
      {white, black} = if white_is_a?, do: {a, b}, else: {b, a}

      cond do
        white == dummy_number -> {:bye, black}
        black == dummy_number -> {:bye, white}
        true -> {:pairing, white, black}
      end
    end)
  end

  ## ---------- pairing numbers ----------

  # Frozen once, forever - the very first call for this tournament (no
  # player has a pairing_number yet). Every later call is a no-op, so
  # players added afterward never get one and are excluded from the
  # schedule (see moduledoc).
  #
  # The freeze itself is the Swiss path's, called rather than copied:
  # `Pairing.active_players/1` for who is eligible at freeze time and
  # `Pairing.ensure_pairing_numbers/2` for the numbering, both exposed for
  # exactly this reuse (Keizer already did it; this module had a
  # hand-written duplicate of each - the same query, and the same
  # `{-rating, name}` sort from FIDE C.04.2.B). They agreed, which is the
  # only reason nothing had gone wrong yet.
  #
  # The `already_frozen?` guard stays HERE and does not move into
  # `ensure_pairing_numbers/2`: that function deliberately numbers any
  # player still lacking a number, which is right for Swiss, where a late
  # entrant joins the field. Round robin must refuse exactly that - the
  # Berger schedule is fixed at freeze time, so a player numbered afterwards
  # would be scheduled against nobody.
  #
  # Before any round exists, numbers already on the roster are the arbiter's
  # own (`PairingsEngine.StartingNumbers` - set by hand or by a drawing of
  # lots, VCL4THP Q95) or an import's, and are kept; anybody active still
  # without one - an entry made after the numbers were set - is numbered on
  # after them, as a late entry joins a drawn table (C.05 6.4: the drawn
  # pairings stay as they were). `ensure_pairing_numbers/2` numbers exactly
  # the players lacking a number, so with nobody numbered this is the
  # rating-order freeze it always was.
  defp ensure_frozen(%Tournament{} = tournament) do
    if not already_frozen?(tournament.id) or Engine.paired_rounds_count(tournament.id) == 0 do
      Engine.ensure_pairing_numbers(tournament, Engine.active_players(tournament.id))
    end

    :ok
  end

  defp already_frozen?(tournament_id) do
    Repo.exists?(
      from p in Player,
        where: p.tournament_id == ^tournament_id and not is_nil(p.pairing_number)
    )
  end

  # See `pair_next_round/1`'s doc - round-robin's real round count is a
  # pure function of the frozen player count plus cycles/match-format,
  # never a free-standing arbiter choice the way it is for Swiss. Fewer
  # than 2 frozen players is a no-op (pair_next_round/1's own guard
  # already refuses to pair in that case; nothing useful to correct to).
  #
  # `groups` is `schedule_groups/2`'s answer: one Berger table per group, and
  # the tournament lasts as long as its longest table.
  defp ensure_correct_rounds_count(tournament, groups) do
    case groups |> Enum.map(&length/1) |> Enum.max(fn -> 0 end) do
      frozen_count when frozen_count >= 2 -> correct_rounds_count(tournament, frozen_count)
      _ -> tournament
    end
  end

  defp correct_rounds_count(tournament, frozen_count) do
    correct =
      if tournament.rr_match_format do
        match_total_rounds(frozen_count)
      else
        total_rounds(frozen_count, tournament.rr_cycles)
      end

    cond do
      tournament.rounds_count == correct ->
        tournament

      true ->
        case Tournaments.update_tournament(tournament, %{rounds_count: correct}) do
          {:ok, updated} ->
            updated

          # `Tournament.changeset/2` caps rounds_count at `max_rounds/0` - a sanity bound
          # on a Swiss field's round picker, written independently of
          # `total_rounds/2`, which derives whatever a Berger schedule
          # actually needs. A 32-player double round robin needs 62, so the
          # two disagree and the hard `{:ok, _} =` match raised MatchError
          # straight out of `pair_next_round/1` - an unhandled crash where
          # every other refusal in this module returns `{:error, reason}` for
          # the LiveView to display.
          #
          # Returned as a tagged tuple rather than raised, and rather than
          # quietly capping: capping would pair a schedule the arbiter did
          # not ask for and silently drop its tail.
          {:error, %Ecto.Changeset{}} ->
            {:error,
             "A round robin with #{frozen_count} players needs #{correct} rounds, " <>
               "which is above the #{Tournament.max_rounds()}-round maximum this app supports. " <>
               "Reduce the field, or use a single cycle instead of a double."}
        end
    end
  end

  # The frozen schedule set: every player who has a pairing_number,
  # regardless of their *current* status/absent/forfeit flags. A
  # round-robin schedule is fixed at freeze time - pulling someone out
  # later would change every other player's opponent for that round, so
  # a player who becomes absent/withdrawn/forfeited after the freeze
  # still gets paired every round; the arbiter records a forfeit result
  # instead (see moduledoc and docs/pairing-systems.md).
  defp frozen_players(tournament_id), do: Engine.full_roster_players(tournament_id)

  ## ---------- the pairing run ----------

  defp do_pair(tournament, frozen, next_number) do
    scheduled =
      tournament
      |> schedule_groups(frozen)
      |> Enum.map(&{&1, group_schedule(tournament, length(&1), next_number)})

    case Enum.find(scheduled, &match?({_group, {:ok, _}}, &1)) do
      nil ->
        # Every table has played all its rounds (or there is none).
        case scheduled do
          [{_group, error} | _] -> error
          [] -> {:error, "At least two active players are needed"}
        end

      _some ->
        result = create_round(tournament, scheduled_matches(scheduled), next_number)

        case result do
          {:ok, _round} -> Tournaments.broadcast_tournament_change(tournament.id, :rounds)
          _ -> :ok
        end

        result
    end
  end

  # Each table's own numbers - 1..n in pairing-number order - turned back
  # into players, table after table, each table's boards lowest number
  # first. One table over the whole field numbers exactly as the pairing
  # numbers do, since a round robin frozen here numbers 1..N; a SWAR
  # import's pairing numbers are SWAR's Berger numbers already (see
  # `SwarImport`'s "pairing numbers"). A table that has played all its
  # rounds, beside a longer one that has not, adds nothing.
  defp scheduled_matches(scheduled) do
    Enum.flat_map(scheduled, fn
      {group, {:ok, group_matches}} ->
        by_number = group |> Enum.with_index(1) |> Map.new(fn {p, i} -> {i, p} end)

        group_matches
        |> Enum.map(fn
          {:pairing, w, b} -> {:pairing, Map.fetch!(by_number, w), Map.fetch!(by_number, b)}
          {:bye, n} -> {:bye, Map.fetch!(by_number, n)}
        end)
        |> Enum.sort_by(fn
          {:pairing, w, b} -> {0, min(w.pairing_number, b.pairing_number)}
          {:bye, p} -> {1, p.pairing_number}
        end)

      {_group, {:error, _}} ->
        []
    end)
  end

  defp group_schedule(tournament, count, next_number) do
    if tournament.rr_match_format do
      match_schedule(count, next_number)
    else
      schedule(count, tournament.rr_cycles, next_number,
        reverse_last_two?: tournament.rr_reverse_last_two == true
      )
    end
  end

  @doc """
  The groups a round robin's Berger tables run over, each in pairing-number
  order: the whole frozen field - or, when the tournament pairs by category,
  one table per category, in the tournament's own category order with the
  uncategorised last. The second is SWAR's round robin with separate
  categories (`PairingRobin.cpp`: one Berger table per category, its
  players numbered by Rank within it). A category of one player has nobody
  to play, and gets no table.
  """
  def schedule_groups(tournament, frozen) do
    if by_category?(tournament) do
      order = (tournament.categories || []) ++ [""]

      frozen
      |> Enum.group_by(&PairingsEngine.Categories.pairing_category(tournament, &1))
      |> Enum.sort_by(fn {name, _players} -> Enum.find_index(order, &(&1 == name)) end)
      |> Enum.map(fn {_name, players} -> Enum.sort_by(players, & &1.pairing_number) end)
      |> Enum.filter(&(length(&1) >= 2))
    else
      [Enum.sort_by(frozen, & &1.pairing_number)]
    end
  end

  defp by_category?(tournament) do
    Map.get(tournament, :pair_by_category) == true and
      Map.get(tournament, :categories_enabled) == true and
      (tournament.categories || []) != []
  end

  defp create_round(tournament, matches, next_number) do
    Repo.transaction(fn ->
      published_at = Tournaments.compute_published_at(tournament, next_number)

      round =
        Repo.insert!(%Round{
          tournament_id: tournament.id,
          number: next_number,
          status: "playing",
          published_at: published_at,
          publish_due_at: Tournaments.due_publish_at(published_at)
        })

      matches
      |> Enum.filter(&match?({:pairing, _, _}, &1))
      |> Enum.with_index(1)
      |> Enum.each(fn {{:pairing, white, black}, board} ->
        Repo.insert!(%Pairing{
          round_id: round.id,
          board: board,
          white_player_id: white.id,
          black_player_id: black.id,
          result: forfeit_result(white, black)
        })
      end)

      {swar_byes, byes} =
        matches
        |> Enum.filter(&match?({:bye, _}, &1))
        |> Enum.split_with(fn _bye -> swar_bye?(tournament) end)

      # A round robin continued from a SWAR file keeps SWAR's free round: a
      # bye board worth `bye_value`, which the import set to the full point
      # SWAR forces on every round robin (`SwarImport.scoring_attrs/1`) - the
      # same shape as the free rounds already imported, so one tournament
      # does not score its first rounds' byes at a point and the rest at
      # nothing.
      pairings_count = Enum.count(matches, &match?({:pairing, _, _}, &1))

      swar_byes
      |> Enum.with_index(pairings_count + 1)
      |> Enum.each(fn {{:bye, player}, board} ->
        Repo.insert!(%Pairing{
          round_id: round.id,
          board: board,
          white_player_id: player.id,
          black_player_id: nil,
          result: "bye"
        })
      end)

      bye_rows =
        byes
        |> Enum.map(fn {:bye, player} ->
          %{
            tournament_id: tournament.id,
            player_id: player.id,
            round: next_number,
            type: "requested-zero"
          }
        end)

      if bye_rows != [] do
        Repo.insert_all("byes", bye_rows, on_conflict: :nothing)

        # A "requested-zero" bye immediately awards points (see
        # PairingsEngine.Standings) without ever going through
        # Tournaments.update_pairing_result/2 - a hand-set manual standings
        # order must be marked stale here too, same as any other
        # point-changing write. See docs/manual-standings.md (Fix 3) and
        # PairingsEngine.Pairing.insert_round_absentee_byes/3 for the same
        # pattern on the Swiss/JaVaFo path. Must run before the caller's
        # broadcast_tournament_change so no PubSub subscriber can reload and
        # observe a stale-but-unmarked manual order.
        Tournaments.invalidate_manual_ranking(tournament.id)
      end

      Tournaments.freeze_round_display_boards!(round.id)

      round
    end)
  end

  # A round robin imported from a SWAR round-robin file (`swar_settings`'
  # "type" is SWAR's ROBIN, ROBIN_DBL or ROBIN_AR).
  defp swar_bye?(tournament) do
    type = Map.get(Map.get(tournament, :swar_settings) || %{}, "type")
    type in [4, 5, 6]
  end

  # A player who is currently `absent` or `forfeit` (both fields bypass
  # `ensure_frozen/1`'s filter identically for tournaments continued from a
  # SWAR import, where `pairing_number` is set directly at player creation -
  # see `PairingsEngine.Federations.BEL.SwarImport`) still gets paired every round by design
  # (see moduledoc: the Berger schedule can't be recomputed mid-tournament),
  # but should never be left with a blank result for the arbiter to notice
  # manually. Automate exactly what the moduledoc already documents: record
  # the forfeit result at insert time instead. `absent` and `forfeit` are
  # treated as equivalent OR-conditions - either one alone is enough to mark
  # a side as forfeiting, and having both set changes nothing.
  defp forfeit_result(%Player{} = white, %Player{} = black) do
    white_out? = white.absent || white.forfeit
    black_out? = black.absent || black.forfeit

    cond do
      white_out? and black_out? -> "0-0FF"
      white_out? -> "0-1FF"
      black_out? -> "1-0FF"
      true -> ""
    end
  end
end
