defmodule PairingsEngine.RoundRobin do
  @moduledoc """
  Round-robin (Berger table) pairing engine.

  `PairingsEngine.Pairing.pair_next_round/1` dispatches here for any
  tournament with `pairing_system: "round_robin"`.

  ## The schedule

  FIDE only publishes finished Berger tables (Handbook C.05 Annex 1, for
  2..16-ish players) rather than a formula, but they're generated by a
  well-defined "circle method" construction that this module reimplements
  and has been verified against the published tables for N=4 and N=6 (see
  `test/pairings_engine/round_robin_test.exs`):

    * Players are numbered 1..N by their frozen `pairing_number` (see
      "Freezing" below). If N is odd, a phantom player numbered N+1 is
      added to make the count even — FIDE's own rule ("where there is an
      odd number of players, the highest number counts as a bye").
    * `effective_n` = N (even) or N+1 (odd); `m = effective_n - 1` (always
      odd, since `effective_n` is always even) is both the number of
      rounds in one cycle and the modulus for the round-robin arithmetic.
    * Player `effective_n` (the highest number — real when N is even, the
      phantom when N is odd) is the *fixed* player: in round `r`
      (0-indexed), it plays whichever real player `f(r) = (r * inv2) rem m`
      is (where `inv2` is the modular inverse of 2 mod `m`, i.e.
      `(m + 1) / 2` since `m` is odd) — this is a bijection over `r`, so
      every player takes the fixed player's opponent slot exactly once per
      cycle. When the fixed player is the phantom, that real opponent gets
      the round's structural bye instead of a real pairing.
    * Every other player `i` (0-indexed label, real number `i + 1`) not
      equal to `f(r)` pairs with `j` such that `i + j ≡ r (mod m)` — the
      remaining `m - 1` labels split into `(m - 1) / 2` such pairs.
    * Colour: for the fixed pairing, the fixed player is White iff `r` is
      odd. For every other pair `(i, j)` with `i < j`, White is the
      lower-numbered player `i` iff `j - i` is odd, otherwise the
      higher-numbered player `j`. Both rules were reverse-engineered from
      the FIDE-published N=4 and N=6 tables and hold for every pair in
      both (all four possible `j - i` distances for N=6, both possible
      distances for N=4) — see `docs/pairing-systems.md`.

  All of this lives in `schedule/3`, which is a **pure** function of
  `(player_count, cycles, round_number)` — pairing round K always produces
  the same result, satisfying the correctness rule that a round-robin
  schedule must not depend on when it's computed.

  ## Freezing pairing numbers

  Exactly like the Swiss path (`PairingsEngine.Pairing`), pairing numbers
  are assigned once — highest rating first, name as the tie-break (FIDE
  C.04.2.B) — and then frozen forever. Unlike Swiss, round robin never
  assigns numbers to anyone after that first freeze: the schedule is fixed
  the moment round 1 is first paired, and it would be structurally
  impossible to slot a newcomer into an already-computed Berger table
  without changing everyone else's opponents. Players who join after the
  freeze are simply excluded from every round of the schedule (see
  `docs/pairing-systems.md`).

  ## Byes

  Odd player counts always produce exactly one structural, zero-point bye
  per player per cycle (never zero, never two) — see `schedule/3`'s doc.
  It's recorded as a `"requested-zero"` row in the `byes` table (TRF code
  `Z`, 0 points via `PairingsEngine.Standings`/`PairingsEngine.Pairing`'s
  existing bye-type handling) with no corresponding `pairings` row — the
  same shape Swiss already uses for a round-specific requested absence.
  `"pairing-allocated"` (a full point) is deliberately not used: this bye
  isn't the pairing engine running out of opponents, it's a structural
  feature of an odd-sized round-robin, and giving it a free point would
  be unfair to the N-1 (or N, if N even) players who never get one.
  """

  import Ecto.Query
  alias PairingsEngine.{Repo, Tournaments}
  alias PairingsEngine.Tournaments.{Player, Round, Pairing, Tournament}

  @doc "Pairs the next round using a Berger round-robin schedule."
  @spec pair_next_round(Tournament.t()) :: {:ok, Round.t()} | {:error, term()}
  def pair_next_round(%Tournament{} = tournament) do
    ensure_frozen(tournament.id)
    frozen = frozen_players(tournament.id)
    paired = PairingsEngine.Pairing.paired_rounds_count(tournament.id)

    # Unlike Swiss, a round-robin round's pairings never depend on prior
    # results (the whole schedule is fixed at freeze time — see moduledoc),
    # so there's no need to gate pairing round N+1 on round N being fully
    # scored the way the Swiss/JaVaFo path does.
    if length(frozen) < 2 do
      {:error, "At least two active players are needed"}
    else
      do_pair(tournament, frozen, paired + 1)
    end
  end

  @doc """
  Computes the Berger schedule for `round_number` (1-indexed, spanning
  however many `cycles` the tournament plays — see `tournaments.rr_cycles`)
  over `player_count` schedulable (frozen) players numbered 1..player_count.

  Pure: touches no database, depends only on these three integers. Returns
  `{:ok, matches}` where each entry is `{:pairing, white_number,
  black_number}` (both 1-indexed pairing numbers) or `{:bye, player_number}`
  (the odd-N structural bye), or `{:error, reason}` once every round of the
  schedule has already been returned.
  """
  @spec schedule(pos_integer(), pos_integer(), pos_integer()) ::
          {:ok, [{:pairing, pos_integer(), pos_integer()} | {:bye, pos_integer()}]}
          | {:error, String.t()}
  def schedule(player_count, cycles, round_number) when player_count >= 2 do
    effective_n = if rem(player_count, 2) == 0, do: player_count, else: player_count + 1
    dummy_number = if rem(player_count, 2) == 1, do: effective_n, else: nil
    cycle_length = effective_n - 1
    total_rounds = cycle_length * cycles

    if round_number > total_rounds do
      {:error, "All rounds have been paired (round-robin schedule complete)"}
    else
      cycle_index = div(round_number - 1, cycle_length)
      r = Integer.mod(round_number - 1, cycle_length)
      reverse_colours? = rem(cycle_index, 2) == 1

      {:ok, round_matches(effective_n, dummy_number, r, reverse_colours?)}
    end
  end

  @doc "Total number of rounds the full schedule needs for `player_count` players over `cycles` cycles."
  def total_rounds(player_count, cycles) do
    effective_n = if rem(player_count, 2) == 0, do: player_count, else: player_count + 1
    (effective_n - 1) * cycles
  end

  @doc """
  "Match format" schedule: like `schedule/3` but every single-cycle pairing
  is played twice, back-to-back, colours reversed, instead of once —
  `tournaments.rr_match_format`, a different shape from `rr_cycles == 2`
  (see the moduledoc and the field's own doc comment on
  `PairingsEngine.Tournaments.Tournament`).

  `physical_round` is the round number as actually paired/displayed (1, 2,
  3, 4, ... — nothing here renumbers rounds). Physical rounds `2k-1` and
  `2k` are match `k`'s two legs: `match_number = div(physical_round + 1, 2)`
  maps both `2k-1` and `2k` to `k`, and `schedule(player_count, 1, k)` gives
  that match's pairing exactly once (a single-cycle Berger table, since a
  "match" here is one cycle's worth of pairing repeated, not two cycles).
  The odd physical round is leg 1, played exactly as the single-cycle
  schedule says; the even physical round is leg 2, the same pairing with
  colours swapped (`mirror_leg/1`).

  A structural bye (odd player count) mirrors unchanged rather than
  swapping anything — the player sitting out match `k` sits out both of its
  legs identically, so leg 2's bye row is the same player, same
  `"requested-zero"` type, just recorded against the next round number by
  the caller (`do_pair/2` inserts one row per physical round, same as
  `schedule/3`).
  """
  @spec match_schedule(pos_integer(), pos_integer()) ::
          {:ok, [{:pairing, pos_integer(), pos_integer()} | {:bye, pos_integer()}]}
          | {:error, String.t()}
  def match_schedule(player_count, physical_round) when physical_round >= 1 do
    match_number = div(physical_round + 1, 2)

    case schedule(player_count, 1, match_number) do
      {:ok, matches} ->
        leg2? = rem(physical_round, 2) == 0
        {:ok, if(leg2?, do: Enum.map(matches, &mirror_leg/1), else: matches)}

      error ->
        error
    end
  end

  defp mirror_leg({:pairing, w, b}), do: {:pairing, b, w}
  defp mirror_leg({:bye, _} = bye), do: bye

  @doc """
  Total number of physical rounds the match-format schedule needs for
  `player_count` players — exactly double `total_rounds(player_count, 1)`,
  since every single-cycle pairing becomes two physical rounds (its two
  legs). Match format is always a single Berger cycle underneath (see
  `match_schedule/2`), so unlike `total_rounds/2` there's no `cycles`
  parameter here.
  """
  @spec match_total_rounds(pos_integer()) :: pos_integer()
  def match_total_rounds(player_count) do
    total_rounds(player_count, 1) * 2
  end

  ## ---------- pure schedule construction ----------

  # See the moduledoc for the derivation of both the pairing and the
  # colour rule. `effective_n` is always even; `dummy_number` is
  # `effective_n` itself when the real player count was odd, else `nil`.
  defp round_matches(effective_n, dummy_number, r, reverse_colours?) do
    m = effective_n - 1
    inv2 = div(m + 1, 2)
    f = Integer.mod(r * inv2, m)

    fixed = {effective_n, f + 1, rem(r, 2) == 1}

    other =
      0..(m - 1)
      |> Enum.reject(&(&1 == f))
      |> Enum.map(fn i -> {i, Integer.mod(r - i, m)} end)
      |> Enum.filter(fn {i, j} -> i < j end)
      |> Enum.map(fn {i, j} -> {i + 1, j + 1, rem(j - i, 2) == 1} end)

    [fixed | other]
    |> Enum.map(fn {a, b, a_white?} ->
      white_is_a? = a_white? != reverse_colours?
      {white, black} = if white_is_a?, do: {a, b}, else: {b, a}

      cond do
        white == dummy_number -> {:bye, black}
        black == dummy_number -> {:bye, white}
        true -> {:pairing, white, black}
      end
    end)
  end

  ## ---------- pairing numbers ----------

  # Frozen once, forever — the very first call for this tournament (no
  # player has a pairing_number yet). Every later call is a no-op, so
  # players added afterward never get one and are excluded from the
  # schedule (see moduledoc). Same ordering rule as the Swiss path
  # (PairingsEngine.Pairing.ensure_pairing_numbers/2): highest rating
  # first, name as the tie-break (FIDE C.04.2.B).
  defp ensure_frozen(tournament_id) do
    already_frozen? =
      Repo.exists?(
        from p in Player,
          where: p.tournament_id == ^tournament_id and not is_nil(p.pairing_number)
      )

    unless already_frozen? do
      Repo.all(
        from p in Player,
          where:
            p.tournament_id == ^tournament_id and p.status == "active" and
              p.absent == false and p.forfeit == false
      )
      |> Enum.sort_by(&{-Player.rating(&1), &1.name})
      |> Enum.with_index(1)
      |> Enum.each(fn {player, number} ->
        {:ok, _} = Tournaments.update_player(player, %{pairing_number: number})
      end)
    end

    :ok
  end

  # The frozen schedule set: every player who has a pairing_number,
  # regardless of their *current* status/absent/forfeit flags. A
  # round-robin schedule is fixed at freeze time — pulling someone out
  # later would change every other player's opponent for that round, so
  # a player who becomes absent/withdrawn/forfeited after the freeze
  # still gets paired every round; the arbiter records a forfeit result
  # instead (see moduledoc and docs/pairing-systems.md).
  defp frozen_players(tournament_id) do
    Repo.all(
      from p in Player,
        where: p.tournament_id == ^tournament_id and not is_nil(p.pairing_number),
        order_by: p.pairing_number
    )
  end

  ## ---------- the pairing run ----------

  defp do_pair(tournament, frozen, next_number) do
    result =
      if tournament.rr_match_format do
        match_schedule(length(frozen), next_number)
      else
        schedule(length(frozen), tournament.rr_cycles, next_number)
      end

    case result do
      {:error, reason} ->
        {:error, reason}

      {:ok, matches} ->
        by_number = Map.new(frozen, &{&1.pairing_number, &1})
        result = create_round(tournament, by_number, matches, next_number)

        case result do
          {:ok, _round} -> Tournaments.broadcast_tournament_change(tournament.id, :rounds)
          _ -> :ok
        end

        result
    end
  end

  defp create_round(tournament, by_number, matches, next_number) do
    Repo.transaction(fn ->
      round =
        Repo.insert!(%Round{
          tournament_id: tournament.id,
          number: next_number,
          status: "playing"
        })

      matches
      |> Enum.filter(&match?({:pairing, _, _}, &1))
      |> Enum.sort_by(fn {:pairing, w, b} -> min(w, b) end)
      |> Enum.with_index(1)
      |> Enum.each(fn {{:pairing, w, b}, board} ->
        white = Map.fetch!(by_number, w)
        black = Map.fetch!(by_number, b)

        Repo.insert!(%Pairing{
          round_id: round.id,
          board: board,
          white_player_id: white.id,
          black_player_id: black.id,
          result: forfeit_result(white, black)
        })
      end)

      bye_rows =
        matches
        |> Enum.filter(&match?({:bye, _}, &1))
        |> Enum.map(fn {:bye, num} ->
          player = Map.fetch!(by_number, num)

          %{
            tournament_id: tournament.id,
            player_id: player.id,
            round: next_number,
            type: "requested-zero"
          }
        end)

      if bye_rows != [] do
        Repo.insert_all("byes", bye_rows)

        # A "requested-zero" bye immediately awards points (see
        # PairingsEngine.Standings) without ever going through
        # Tournaments.update_pairing_result/2 — a hand-set manual standings
        # order must be marked stale here too, same as any other
        # point-changing write. See docs/manual-standings.md (Fix 3) and
        # PairingsEngine.Pairing.insert_round_absentee_byes/3 for the same
        # pattern on the Swiss/JaVaFo path. Must run before the caller's
        # broadcast_tournament_change so no PubSub subscriber can reload and
        # observe a stale-but-unmarked manual order.
        Tournaments.invalidate_manual_ranking(tournament.id)
      end

      round
    end)
  end

  # A player who is currently `absent` or `forfeit` (both fields bypass
  # `ensure_frozen/1`'s filter identically for tournaments continued from a
  # SWAR import, where `pairing_number` is set directly at player creation —
  # see `PairingsEngine.SwarImport`) still gets paired every round by design
  # (see moduledoc: the Berger schedule can't be recomputed mid-tournament),
  # but should never be left with a blank result for the arbiter to notice
  # manually. Automate exactly what the moduledoc already documents: record
  # the forfeit result at insert time instead. `absent` and `forfeit` are
  # treated as equivalent OR-conditions — either one alone is enough to mark
  # a side as forfeiting, and having both set changes nothing.
  defp forfeit_result(%Player{} = white, %Player{} = black) do
    white_out? = white.absent || white.forfeit
    black_out? = black.absent || black.forfeit

    cond do
      white_out? and black_out? -> "0-0FF"
      white_out? -> "0-1FF"
      black_out? -> "1-0FF"
      true -> ""
    end
  end
end
