<#
.SYNOPSIS
    Builds OpenPairings.exe, the launcher that starts the portable release.

.DESCRIPTION
    `launcher.c` is the whole program and its header comment is the whole
    rationale; this script only compiles it. It exists so the build is a
    command anybody can re-run rather than a binary somebody once produced -
    the same reason build_brand_assets.py exists next door.

    Nothing here is Windows-only except the target. `zig cc` cross-compiles,
    so this also runs from a Linux or macOS host if that is ever wanted; it is
    written in PowerShell because that is what the Windows build already
    speaks.

    Normally you do not run this by hand at all: `mix release
    pairings_engine_portable` runs it as a release step and drops the result
    into the release root, where Velopack's --mainExe needs it. Run it
    directly when you are working on the launcher itself.

.NOTES
    Why Zig and not a "real" toolchain: it is already this project's build
    dependency (Burrito needs it - see docs/binaries.md), it ships its own
    libc and Windows headers so there is no Visual Studio to install, and it
    produces about 100 KB with no runtime behind it. The alternative that
    keeps suggesting itself is .NET, and it is wrong twice: framework-
    dependent needs a runtime on the arbiter's machine, which is exactly what
    the portable release promises there is not, and self-contained adds ~60 MB
    to a payload that is already 155 MB.

    Zig version: CI pins 0.15.2 because Burrito 1.5 requires exactly that, and
    a developer machine may have anything newer. Only `zig cc` and `zig rc`
    are used here, and both are drop-in compatible interfaces (clang and
    rc.exe) rather than Zig-language APIs, so the pin does not matter to this
    file. That is also why launcher.c is C: Zig's own standard library does
    change shape between releases.
#>

[CmdletBinding()]
param(
    # Defaults beside the sources, which is a scratch location - .gitignored.
    # The release step passes the release root instead.
    [string]$OutputPath = "$PSScriptRoot\OpenPairings.exe",

    # Stamped into the VERSIONINFO resource. Defaults to mix.exs so the
    # executable's Properties page cannot disagree with the app it starts.
    [string]$Version,

    # For a build machine where zig is installed but not on PATH.
    [string]$Zig = 'zig'
)

$ErrorActionPreference = 'Stop'

if (-not (Get-Command $Zig -ErrorAction SilentlyContinue)) {
    throw "zig not found. Install it (scoop install zig, brew install zig) or pass -Zig <path>."
}

if (-not $Version) {
    $mixExs = Join-Path $PSScriptRoot '..\..\mix.exs'
    $match = Select-String -Path $mixExs -Pattern 'version:\s*"([0-9]+\.[0-9]+\.[0-9]+)"' |
        Select-Object -First 1
    if (-not $match) { throw "Could not read the version from mix.exs; pass -Version." }
    $Version = $match.Matches[0].Groups[1].Value
}

$parts = $Version.Split('.')
if ($parts.Count -ne 3) { throw "Version must be MAJOR.MINOR.PATCH, got '$Version'." }

$objDir = Join-Path $PSScriptRoot 'obj'
New-Item -ItemType Directory -Force -Path $objDir | Out-Null

# Generated rather than committed: a version constant that has to be edited by
# hand is a version constant that goes stale, and this project already has a
# `mix pairings.version_check` because that keeps happening.
$header = Join-Path $objDir 'launcher_version.h'
@"
/* Generated by build_launcher.ps1 - do not edit, do not commit. */
#define OP_VER_MAJOR $($parts[0])
#define OP_VER_MINOR $($parts[1])
#define OP_VER_PATCH $($parts[2])
#define OP_VER_STRING "$Version"
"@ | Out-File -FilePath $header -Encoding ascii

$res = Join-Path $objDir 'launcher.res'

Push-Location $PSScriptRoot
try {
    # Options before the input file: `zig rc` stops parsing options at the
    # first non-option argument, so `zig rc launcher.rc /fo out.res` reads /fo
    # as a path. Run from this directory so the ICON and manifest lines resolve
    # relative to the .rc.
    & $Zig rc /nologo /i $objDir /fo $res launcher.rc
    if ($LASTEXITCODE -ne 0) { throw "zig rc failed with exit code $LASTEXITCODE" }

    # -target rather than the host default, so a build on any machine produces
    #   the same file for the same audience.
    # -Os -s because this is a launcher, not a hot loop: 90 KB against 220 KB
    #   for the same program at -O2 with symbols.
    # /subsystem:windows is what makes it a GUI program - i.e. what stops
    #   Windows allocating a console window for it. That is requirement three
    #   of four, and it is one linker flag.
    & $Zig cc `
        -target x86_64-windows-gnu `
        -Os -s `
        -Wall -Wextra `
        "-Wl,/subsystem:windows" `
        launcher.c $res `
        -o $OutputPath `
        -luser32 -lgdi32 -lshell32 -lole32 -lcomctl32 -lws2_32
    if ($LASTEXITCODE -ne 0) { throw "zig cc failed with exit code $LASTEXITCODE" }
}
finally {
    Pop-Location
}

Get-Item $OutputPath |
    Select-Object Name, @{n = 'KB'; e = { [math]::Round($_.Length / 1KB, 1) } }, FullName |
    Format-Table -AutoSize
